defaultTheme = "dark"
ShowReadingTime = false
ShowWordCount = false
ShowBreadCrumbs = false
ShowPostNavLinks = false
ShowDate = true
ShowSearchBar = true

[cover]
  hidden = false
  hiddenInList = false
  hiddenInSingle = true


